feature :: introduce s3 bucket with docker container
ToucanToco/peakina pull request #28
Opened 2020-03-13 09:54 UTC by QuentinMadura

This PR introduce:

- the capacity to run a docker container
- the ability to run an Amazon s3 bucket as a storage inside a docker container.

2020-03-13 16:23 UTC, PrettyWood requested changes

2020-03-13 16:23 UTC, PrettyWood commented on setup.cfg
> +    docker
these dependencies are only for tests. Please move them in the `extras_require` test section

2020-03-15 20:47 UTC, piotch requested changes
@QuentinMadura could you do these changes in a branch starting from `f/s3_match_true` or directly in this branch, since we are going to use this for writing the tests

2020-03-15 22:19 UTC, PrettyWood commented
@piotch Actually I'm in favor of two distinct pull requests : one to add the docker pytest fixture + test the existing s3 code with a container and another one, which actually adds the match support by implementing listdir

2020-03-22 21:05 UTC, closed without merging