fix: connection dropped for refresh-data [TCTC-6839]
ToucanToco/peakina pull request #600
Opened 2023-10-03 14:42 UTC by Sanix-Darker

## WHAT

`connection dropped` on remote file (SFTP).
This is not a "new issue", my proposition on this PR is to increase the timeout, the retry and
suppress the .close() error and let see on live prod how it behave.

## HOW

- feat: increase timeout values and the retry amount
- fix: suppress the .close error for None type ?

2023-10-03 15:09 UTC, WilliamGorge requested changes
Merci

2023-10-03 15:09 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +_DEFAULT_MAX_TIMEOUT = 10
tu peux spécifier l'unité dans la constante?
```suggestion
_DEFAULT_MAX_TIMEOUT_SECONDS = 10
```

2023-10-03 15:26 UTC, Sanix-Darker commented on peakina/io/ftp/ftp_utils.py
> +_DEFAULT_MAX_TIMEOUT = 10
https://github.com/toucantoco/peakina/pull/600/commits/e4e4a5d

2023-10-03 15:49 UTC, WilliamGorge approved these changes

2023-10-03 15:49 UTC, WilliamGorge commented
on merge pas tant qu'on n'est pas sur

2023-10-06 12:29 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +                    url.split("/")[-1] + " not found !"
j'aurais mis toute l'url

2023-10-06 12:30 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +            if isinstance(e, FileNotFoundError):
tu peuxrajouter un gros try/except pour ce bloc au cas ou y'a une erreur? pour éviter de crash dans le fallback

2023-10-06 12:30 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +            # TODO: remove this after the debuging is done !
pour moi on peut le garder... à voir

2023-10-06 12:30 UTC, Sanix-Darker commented on peakina/io/ftp/ftp_utils.py
> +                    url.split("/")[-1] + " not found !"
ok, jusqu'au path ducoup, parcequ'il y'a des creds dedans 😬 
j'update cela !

2023-10-06 12:31 UTC, Sanix-Darker commented on peakina/io/ftp/ftp_utils.py
> +            if isinstance(e, FileNotFoundError):
alright !

2023-10-06 12:49 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +                    url.split("/")[-1] + " not found !"
ah!

2023-10-06 12:49 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +                    url.split("/")[-1] + " not found !"
dans ce cas tant pis

2023-10-06 12:51 UTC, Sanix-Darker commented on peakina/io/ftp/ftp_utils.py
> +                    url.split("/")[-1] + " not found !"
No worries : https://github.com/toucantoco/peakina/pull/600/commits/752f10a

2023-10-06 12:57 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +                    pass # fail in silent
non faut log ou raise

2023-10-09 13:04 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +                    log.warning(f"List of files : ({files_available})")
ça serait plus simple et lisible d'avoir qu'un seul log

2023-10-13 13:14 UTC, Sanix-Darker commented on peakina/io/ftp/ftp_utils.py
> +                    log.warning(f"List of files : ({files_available})")
Updates here : https://github.com/toucantoco/peakina/pull/600/commits/a72fc9c

2023-10-13 13:29 UTC, WilliamGorge requested changes, later dismissed

2023-10-13 13:29 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +_DEFAULT_MAX_RETRY = 7
tu augmente quand même le timeout et les retry?

2023-10-13 13:29 UTC, WilliamGorge commented on peakina/io/ftp/ftp_utils.py
> +            ssh_client.close()
je loggerait quand même le cas ou on arrive pas à close du coup

2023-10-13 13:40 UTC, Sanix-Darker commented on peakina/io/ftp/ftp_utils.py
> +_DEFAULT_MAX_RETRY = 7
le retry etait 4
le timeout etait 3

Tu suggeres que je remettes ces valeurs ?
Je me disais que ces valeurs ne sont pas deconantes non plus.

et  si tu regardes la valeur du timeout par defaut de la calsse FTP, il etait a 60s  : https://github.com/toucantoco/peakina/blob/main/peakina/io/ftp/ftp_utils.py#L27

2023-10-13 13:44 UTC, Sanix-Darker commented on peakina/io/ftp/ftp_utils.py
> +            ssh_client.close()
https://github.com/toucantoco/peakina/pull/600/commits/006ebab

2023-10-13 14:49 UTC, fspot approved these changes

2023-10-13 15:04 UTC, merged